# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Michael\Documents\GitHub\PythonPortfolio.BugTracker\PythonPortfolio.BugTracker\Admin Tools\Python\SupportClasses\dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(644, 749)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(626, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tbBugs = QtWidgets.QWidget()
        self.tbBugs.setObjectName("tbBugs")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tbBugs)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tblwBugs = QtWidgets.QTableWidget(self.tbBugs)
        self.tblwBugs.setMinimumSize(QtCore.QSize(0, 200))
        self.tblwBugs.setMaximumSize(QtCore.QSize(16777215, 400))
        self.tblwBugs.setObjectName("tblwBugs")
        self.tblwBugs.setColumnCount(7)
        self.tblwBugs.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblwBugs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwBugs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwBugs.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwBugs.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwBugs.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwBugs.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwBugs.setHorizontalHeaderItem(6, item)
        self.tblwBugs.horizontalHeader().setDefaultSectionSize(150)
        self.verticalLayout_3.addWidget(self.tblwBugs)
        self.line = QtWidgets.QFrame(self.tbBugs)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.tbBugs)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txtBugDetails = QtWidgets.QLineEdit(self.tbBugs)
        self.txtBugDetails.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txtBugDetails.setObjectName("txtBugDetails")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtBugDetails)
        self.label_2 = QtWidgets.QLabel(self.tbBugs)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_4 = QtWidgets.QLabel(self.tbBugs)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_3 = QtWidgets.QLabel(self.tbBugs)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.deBugDateCreated = QtWidgets.QDateEdit(self.tbBugs)
        self.deBugDateCreated.setObjectName("deBugDateCreated")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.deBugDateCreated)
        self.label_5 = QtWidgets.QLabel(self.tbBugs)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.cmbBugStatus = QtWidgets.QComboBox(self.tbBugs)
        self.cmbBugStatus.setObjectName("cmbBugStatus")
        self.cmbBugStatus.addItem("")
        self.cmbBugStatus.addItem("")
        self.cmbBugStatus.addItem("")
        self.cmbBugStatus.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cmbBugStatus)
        self.label_6 = QtWidgets.QLabel(self.tbBugs)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.rdoBugKnown = QtWidgets.QRadioButton(self.tbBugs)
        self.rdoBugKnown.setMaximumSize(QtCore.QSize(80, 16777215))
        self.rdoBugKnown.setObjectName("rdoBugKnown")
        self.gridLayout.addWidget(self.rdoBugKnown, 1, 0, 1, 1)
        self.rdoBugUnknown = QtWidgets.QRadioButton(self.tbBugs)
        self.rdoBugUnknown.setMaximumSize(QtCore.QSize(80, 50))
        self.rdoBugUnknown.setObjectName("rdoBugUnknown")
        self.gridLayout.addWidget(self.rdoBugUnknown, 0, 0, 1, 1)
        self.dteBugResolution = QtWidgets.QDateTimeEdit(self.tbBugs)
        self.dteBugResolution.setObjectName("dteBugResolution")
        self.gridLayout.addWidget(self.dteBugResolution, 1, 1, 1, 1)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.gridLayout)
        self.txtBugSource = QtWidgets.QLineEdit(self.tbBugs)
        self.txtBugSource.setObjectName("txtBugSource")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtBugSource)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_12 = QtWidgets.QLabel(self.tbBugs)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tbBugs)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.txtBugArgs = QtWidgets.QLineEdit(self.tbBugs)
        self.txtBugArgs.setObjectName("txtBugArgs")
        self.gridLayout_2.addWidget(self.txtBugArgs, 0, 1, 1, 1)
        self.txtBugKwargs = QtWidgets.QLineEdit(self.tbBugs)
        self.txtBugKwargs.setObjectName("txtBugKwargs")
        self.gridLayout_2.addWidget(self.txtBugKwargs, 1, 1, 1, 1)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.gridLayout_2)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.groupBox = QtWidgets.QGroupBox(self.tbBugs)
        self.groupBox.setMinimumSize(QtCore.QSize(150, 258))
        self.groupBox.setMaximumSize(QtCore.QSize(150, 258))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btnBugInsert = QtWidgets.QPushButton(self.groupBox)
        self.btnBugInsert.setMinimumSize(QtCore.QSize(100, 0))
        self.btnBugInsert.setObjectName("btnBugInsert")
        self.verticalLayout_8.addWidget(self.btnBugInsert)
        self.btnBugUpdate = QtWidgets.QPushButton(self.groupBox)
        self.btnBugUpdate.setObjectName("btnBugUpdate")
        self.verticalLayout_8.addWidget(self.btnBugUpdate)
        self.btnBugDelete = QtWidgets.QPushButton(self.groupBox)
        self.btnBugDelete.setObjectName("btnBugDelete")
        self.verticalLayout_8.addWidget(self.btnBugDelete)
        self.btnBugClear = QtWidgets.QPushButton(self.groupBox)
        self.btnBugClear.setObjectName("btnBugClear")
        self.verticalLayout_8.addWidget(self.btnBugClear)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tbBugs, "")
        self.tabAdmin = QtWidgets.QWidget()
        self.tabAdmin.setObjectName("tabAdmin")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabAdmin)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tblwAdmin = QtWidgets.QTableWidget(self.tabAdmin)
        self.tblwAdmin.setMinimumSize(QtCore.QSize(0, 200))
        self.tblwAdmin.setMaximumSize(QtCore.QSize(16777215, 400))
        self.tblwAdmin.setObjectName("tblwAdmin")
        self.tblwAdmin.setColumnCount(6)
        self.tblwAdmin.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblwAdmin.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwAdmin.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwAdmin.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwAdmin.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwAdmin.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwAdmin.setHorizontalHeaderItem(5, item)
        self.tblwAdmin.horizontalHeader().setDefaultSectionSize(150)
        self.verticalLayout_2.addWidget(self.tblwAdmin)
        self.line_2 = QtWidgets.QFrame(self.tabAdmin)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.tabAdmin)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.tabAdmin)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_10 = QtWidgets.QLabel(self.tabAdmin)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_9 = QtWidgets.QLabel(self.tabAdmin)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_14 = QtWidgets.QLabel(self.tabAdmin)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.txtAdminUserName = QtWidgets.QLineEdit(self.tabAdmin)
        self.txtAdminUserName.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txtAdminUserName.setObjectName("txtAdminUserName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtAdminUserName)
        self.txtAdminFirstName = QtWidgets.QLineEdit(self.tabAdmin)
        self.txtAdminFirstName.setObjectName("txtAdminFirstName")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtAdminFirstName)
        self.txtAdminLastName = QtWidgets.QLineEdit(self.tabAdmin)
        self.txtAdminLastName.setObjectName("txtAdminLastName")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtAdminLastName)
        self.txtAdminPassword = QtWidgets.QLineEdit(self.tabAdmin)
        self.txtAdminPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtAdminPassword.setObjectName("txtAdminPassword")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtAdminPassword)
        self.txtAdminEmail = QtWidgets.QLineEdit(self.tabAdmin)
        self.txtAdminEmail.setObjectName("txtAdminEmail")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtAdminEmail)
        self.horizontalLayout_3.addLayout(self.formLayout_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabAdmin)
        self.groupBox_2.setMinimumSize(QtCore.QSize(150, 258))
        self.groupBox_2.setMaximumSize(QtCore.QSize(150, 258))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btnAdminInsert = QtWidgets.QPushButton(self.groupBox_2)
        self.btnAdminInsert.setMinimumSize(QtCore.QSize(100, 0))
        self.btnAdminInsert.setObjectName("btnAdminInsert")
        self.verticalLayout_6.addWidget(self.btnAdminInsert)
        self.btnAdminUpdate = QtWidgets.QPushButton(self.groupBox_2)
        self.btnAdminUpdate.setObjectName("btnAdminUpdate")
        self.verticalLayout_6.addWidget(self.btnAdminUpdate)
        self.btnAdminDelete = QtWidgets.QPushButton(self.groupBox_2)
        self.btnAdminDelete.setObjectName("btnAdminDelete")
        self.verticalLayout_6.addWidget(self.btnAdminDelete)
        self.btnAdminClear = QtWidgets.QPushButton(self.groupBox_2)
        self.btnAdminClear.setObjectName("btnAdminClear")
        self.verticalLayout_6.addWidget(self.btnAdminClear)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tabAdmin, "")
        self.tabListeners = QtWidgets.QWidget()
        self.tabListeners.setObjectName("tabListeners")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabListeners)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tblwListeners = QtWidgets.QTableWidget(self.tabListeners)
        self.tblwListeners.setMinimumSize(QtCore.QSize(0, 200))
        self.tblwListeners.setMaximumSize(QtCore.QSize(16777215, 400))
        self.tblwListeners.setObjectName("tblwListeners")
        self.tblwListeners.setColumnCount(3)
        self.tblwListeners.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblwListeners.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwListeners.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwListeners.setHorizontalHeaderItem(2, item)
        self.tblwListeners.horizontalHeader().setDefaultSectionSize(150)
        self.verticalLayout_4.addWidget(self.tblwListeners)
        self.line_3 = QtWidgets.QFrame(self.tabListeners)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_4.addWidget(self.line_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_13 = QtWidgets.QLabel(self.tabListeners)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.cmbListenersUserName = QtWidgets.QComboBox(self.tabListeners)
        self.cmbListenersUserName.setObjectName("cmbListenersUserName")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmbListenersUserName)
        self.label_16 = QtWidgets.QLabel(self.tabListeners)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.cmbListenersBugSource = QtWidgets.QComboBox(self.tabListeners)
        self.cmbListenersBugSource.setObjectName("cmbListenersBugSource")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbListenersBugSource)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout_3.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.gridLayout_3)
        self.horizontalLayout_4.addLayout(self.formLayout_3)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabListeners)
        self.groupBox_3.setMinimumSize(QtCore.QSize(150, 258))
        self.groupBox_3.setMaximumSize(QtCore.QSize(150, 258))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.btnListenersInsert = QtWidgets.QPushButton(self.groupBox_3)
        self.btnListenersInsert.setMinimumSize(QtCore.QSize(100, 0))
        self.btnListenersInsert.setObjectName("btnListenersInsert")
        self.verticalLayout_9.addWidget(self.btnListenersInsert)
        self.btnListenersUpdate = QtWidgets.QPushButton(self.groupBox_3)
        self.btnListenersUpdate.setObjectName("btnListenersUpdate")
        self.verticalLayout_9.addWidget(self.btnListenersUpdate)
        self.btnListenersDelete = QtWidgets.QPushButton(self.groupBox_3)
        self.btnListenersDelete.setObjectName("btnListenersDelete")
        self.verticalLayout_9.addWidget(self.btnListenersDelete)
        self.btnListenersClear = QtWidgets.QPushButton(self.groupBox_3)
        self.btnListenersClear.setObjectName("btnListenersClear")
        self.verticalLayout_9.addWidget(self.btnListenersClear)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tabListeners, "")
        self.tabBackup = QtWidgets.QWidget()
        self.tabBackup.setObjectName("tabBackup")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabBackup)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tblwBackup = QtWidgets.QTableWidget(self.tabBackup)
        self.tblwBackup.setMinimumSize(QtCore.QSize(0, 200))
        self.tblwBackup.setMaximumSize(QtCore.QSize(16777215, 400))
        self.tblwBackup.setObjectName("tblwBackup")
        self.tblwBackup.setColumnCount(3)
        self.tblwBackup.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblwBackup.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwBackup.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblwBackup.setHorizontalHeaderItem(2, item)
        self.tblwBackup.horizontalHeader().setCascadingSectionResizes(False)
        self.tblwBackup.horizontalHeader().setDefaultSectionSize(150)
        self.tblwBackup.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_5.addWidget(self.tblwBackup)
        self.line_4 = QtWidgets.QFrame(self.tabBackup)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_5.addWidget(self.line_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_19 = QtWidgets.QLabel(self.tabBackup)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_20 = QtWidgets.QLabel(self.tabBackup)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.formLayout_4.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.gridLayout_4)
        self.cmbListener = QtWidgets.QComboBox(self.tabBackup)
        self.cmbListener.setObjectName("cmbListener")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmbListener)
        self.cmbBackup = QtWidgets.QComboBox(self.tabBackup)
        self.cmbBackup.setObjectName("cmbBackup")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbBackup)
        self.horizontalLayout_5.addLayout(self.formLayout_4)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabBackup)
        self.groupBox_4.setMinimumSize(QtCore.QSize(150, 258))
        self.groupBox_4.setMaximumSize(QtCore.QSize(150, 258))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.btnBackupInsert = QtWidgets.QPushButton(self.groupBox_4)
        self.btnBackupInsert.setMinimumSize(QtCore.QSize(100, 0))
        self.btnBackupInsert.setObjectName("btnBackupInsert")
        self.verticalLayout_11.addWidget(self.btnBackupInsert)
        self.btnBackupUpdate = QtWidgets.QPushButton(self.groupBox_4)
        self.btnBackupUpdate.setObjectName("btnBackupUpdate")
        self.verticalLayout_11.addWidget(self.btnBackupUpdate)
        self.btnBackupDelete = QtWidgets.QPushButton(self.groupBox_4)
        self.btnBackupDelete.setObjectName("btnBackupDelete")
        self.verticalLayout_11.addWidget(self.btnBackupDelete)
        self.btnBackupClear = QtWidgets.QPushButton(self.groupBox_4)
        self.btnBackupClear.setObjectName("btnBackupClear")
        self.verticalLayout_11.addWidget(self.btnBackupClear)
        self.horizontalLayout_5.addWidget(self.groupBox_4)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_5.addLayout(self.verticalLayout_14)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tabBackup, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 644, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actLogOut = QtWidgets.QAction(MainWindow)
        self.actLogOut.setObjectName("actLogOut")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionRefresh = QtWidgets.QAction(MainWindow)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actExit = QtWidgets.QAction(MainWindow)
        self.actExit.setObjectName("actExit")
        self.menuFile.addAction(self.actionRefresh)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actLogOut)
        self.menuFile.addAction(self.actExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionHelp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BugTracker Admin Dashboard"))
        item = self.tblwBugs.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Row ID"))
        item = self.tblwBugs.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Details"))
        item = self.tblwBugs.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Arguments"))
        item = self.tblwBugs.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Source"))
        item = self.tblwBugs.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date Created"))
        item = self.tblwBugs.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tblwBugs.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Expected Resolution"))
        self.label.setText(_translate("MainWindow", "Details: "))
        self.label_2.setText(_translate("MainWindow", "Arguments: "))
        self.label_4.setText(_translate("MainWindow", "Date Created: "))
        self.label_3.setText(_translate("MainWindow", "Source: "))
        self.label_5.setText(_translate("MainWindow", "Status: "))
        self.cmbBugStatus.setItemText(0, _translate("MainWindow", "New"))
        self.cmbBugStatus.setItemText(1, _translate("MainWindow", "In Progress"))
        self.cmbBugStatus.setItemText(2, _translate("MainWindow", "Resolved"))
        self.cmbBugStatus.setItemText(3, _translate("MainWindow", "On Hold"))
        self.label_6.setText(_translate("MainWindow", "Expected Resolution: "))
        self.rdoBugKnown.setText(_translate("MainWindow", "Date-Time"))
        self.rdoBugUnknown.setText(_translate("MainWindow", "Unkown"))
        self.label_12.setText(_translate("MainWindow", "Kwargs: "))
        self.label_11.setText(_translate("MainWindow", "Args:"))
        self.groupBox.setTitle(_translate("MainWindow", "Functions"))
        self.btnBugInsert.setText(_translate("MainWindow", "Insert"))
        self.btnBugUpdate.setText(_translate("MainWindow", "Update"))
        self.btnBugDelete.setText(_translate("MainWindow", "Delete"))
        self.btnBugClear.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbBugs), _translate("MainWindow", "Bugs"))
        item = self.tblwAdmin.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Row ID"))
        item = self.tblwAdmin.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "User Name"))
        item = self.tblwAdmin.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "First Name"))
        item = self.tblwAdmin.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.tblwAdmin.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tblwAdmin.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Password"))
        self.label_7.setText(_translate("MainWindow", "First Name: "))
        self.label_8.setText(_translate("MainWindow", "Last Name: "))
        self.label_10.setText(_translate("MainWindow", "Email: "))
        self.label_9.setText(_translate("MainWindow", "Password: "))
        self.label_14.setText(_translate("MainWindow", "User Name: "))
        self.groupBox_2.setTitle(_translate("MainWindow", "Functions"))
        self.btnAdminInsert.setText(_translate("MainWindow", "Insert"))
        self.btnAdminUpdate.setText(_translate("MainWindow", "Update"))
        self.btnAdminDelete.setText(_translate("MainWindow", "Delete"))
        self.btnAdminClear.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAdmin), _translate("MainWindow", "Admin"))
        item = self.tblwListeners.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Row ID"))
        item = self.tblwListeners.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "User Name"))
        item = self.tblwListeners.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Bug Source"))
        self.label_13.setText(_translate("MainWindow", "User Name: "))
        self.label_16.setText(_translate("MainWindow", "Bug Source: "))
        self.groupBox_3.setTitle(_translate("MainWindow", "Functions"))
        self.btnListenersInsert.setText(_translate("MainWindow", "Insert"))
        self.btnListenersUpdate.setText(_translate("MainWindow", "Update"))
        self.btnListenersDelete.setText(_translate("MainWindow", "Delete"))
        self.btnListenersClear.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabListeners), _translate("MainWindow", "Listeners"))
        item = self.tblwBackup.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Row ID"))
        item = self.tblwBackup.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Listener User Name"))
        item = self.tblwBackup.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Backup User Name"))
        self.label_19.setText(_translate("MainWindow", "Listener: "))
        self.label_20.setText(_translate("MainWindow", "Backup: "))
        self.groupBox_4.setTitle(_translate("MainWindow", "Functions"))
        self.btnBackupInsert.setText(_translate("MainWindow", "Insert"))
        self.btnBackupUpdate.setText(_translate("MainWindow", "Update"))
        self.btnBackupDelete.setText(_translate("MainWindow", "Delete"))
        self.btnBackupClear.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBackup), _translate("MainWindow", "Backup Listeners"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actLogOut.setText(_translate("MainWindow", "Log out"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh Tables"))
        self.actExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

